# Generated by Django 2.2.7 on 2019-11-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('plot', models.TextField()),
                ('release_date', models.DateField(null=True)),
                ('running_time', models.IntegerField(default=90)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('imdb_rating', models.FloatField()),
            ],
        ),
    ]
